---
title: "Sample Size Calculation"
author: "Yingxin Lin"
date: "27/08/2019"
output:
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    fig_height: 8
    fig_width: 8
    toc_float:
      collapsed: true
      smooth_scroll: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE)
```

# Functions and results

```{r}
library(scdney)
library(ggplot2)
library(ggthemes)
library(scales)
library(ggpubr)
library(ggforce)
library(reshape2)
library(gridExtra)
library(scClassify)
```


# PBMC10k Level1

```{r fig.show = "hide"}

pbmc10k_level1_sampleCalRes_unblance_pilot <- readRDS("results/pbmc10k_level1_sampleCalRes_unblance_pilot_N1000.rds")
pbmc10k_level1_sampleCalRes_unblance_train <- readRDS("results/pbmc10k_level1_sampleCalRes_unblance_train_N1000.rds")


pilot_correct <- melt(lapply(pbmc10k_level1_sampleCalRes_unblance_pilot, function(x) unlist(lapply(x, "[[", "correct"))))

pilot_correct$L1 <- factor(pilot_correct$L1, levels = (unique(pilot_correct$L1)))


train_correct <- melt(lapply(pbmc10k_level1_sampleCalRes_unblance_train[1:17], function(x) unlist(lapply(x, "[[", "correct"))))

train_correct$L1 <- factor(train_correct$L1, levels = (unique(train_correct$L1)))

# ggplot(train_correct, aes(x = L1, y = value)) +
#   geom_boxplot() +
#   geom_jitter() +
#   theme_bw()


train_correct$type <- "train"
pilot_correct$type <- "pilot"
df_cbind <- rbind(pilot_correct, train_correct)

g1_level1 <- ggplot(df_cbind, aes(x = L1, y = value, color = type)) +
  geom_boxplot() + geom_jitter(alpha = 0.3) +
  scale_color_brewer(palette = "Set1") +
  theme_bw() +
  facet_wrap(~type, scales = "free_x") +
  xlab("N") + ylab("Classification Rate")
g1_level1
ggsave("figures/FigureEV3A_boxplot_learningCurve_pbmc10k_level1.pdf", width = 12, height = 5)
```



## Fitting learning curve


```{r}
acc_pbmc10k_level1_pilot <- lapply(pbmc10k_level1_sampleCalRes_unblance_pilot, function(x) unlist(lapply(x, "[[", "correct")))
acc_pbmc10k_level1_pilot <- acc_pbmc10k_level1_pilot[!is.null(acc_pbmc10k_level1_pilot)]
acc_pbmc10k_level1_pilot <- do.call(cbind, acc_pbmc10k_level1_pilot)
res_pbmc10k_level1_pilot <- learningCurve(acc_pbmc10k_level1_pilot,
                                  as.numeric(colnames(acc_pbmc10k_level1_pilot)),
                                  b = 0.95)
```



```{r}
acc_pbmc10k_level1_train <- lapply(pbmc10k_level1_sampleCalRes_unblance_train, function(x) unlist(lapply(x, "[[", "correct")))
acc_pbmc10k_level1_train <- acc_pbmc10k_level1_train[!is.null(acc_pbmc10k_level1_train)]
acc_pbmc10k_level1_train <- do.call(cbind, acc_pbmc10k_level1_train)
res_pbmc10k_level1_train <- learningCurve(acc_pbmc10k_level1_train,
                                  as.numeric(colnames(acc_pbmc10k_level1_train)),
                                  b = 0.98)
```



```{r}

library(scales)


cols <- c("Pilot" = "indianred",
          "Quantile25/75" = "lightpink3" ,
          "Quantile05/95" = "white", 
          "Train/Test" = "dodgerblue4")

data_pbmc10k_level1_pilot <- data.frame(mean = colMeans(acc_pbmc10k_level1_pilot),
                         n = as.numeric(colnames(acc_pbmc10k_level1_pilot)))

data_pbmc10k_level1_train <- data.frame(mean = colMeans(acc_pbmc10k_level1_train),
                         n = as.numeric(colnames(acc_pbmc10k_level1_train)))



fit_pbmc10k_level1_pilot <- data.frame(n = seq(20,6000, 0.1))
fit_pbmc10k_level1_pilot$mean <- predict(res_pbmc10k_level1_pilot$model$mean, newdata = fit_pbmc10k_level1_pilot)
fit_pbmc10k_level1_pilot$quantile_25 <- predict(res_pbmc10k_level1_pilot$model$quantile_25, newdata = fit_pbmc10k_level1_pilot)
fit_pbmc10k_level1_pilot$quantile_75 <- predict(res_pbmc10k_level1_pilot$model$quantile_75, newdata = fit_pbmc10k_level1_pilot)




ggplot(data = fit_pbmc10k_level1_pilot)  +
  xlab("N") + ylab("Classification Rate") +
  labs(title = "PBMC10k Level1") +
  geom_point(data = data_pbmc10k_level1_pilot, aes(x = n, y = mean, color = "Pilot")) +
  geom_point(data = data_pbmc10k_level1_train, aes(x = n, y = mean, color = "Train/Test")) +
  geom_line(aes(x = n, y = mean, color = "Pilot"), linetype = "solid", size = 1) +
  geom_line(aes(x = n, y = quantile_25, color = "Quantile25/75"), linetype = "dashed") +
  geom_line(aes(x = n, y = quantile_75, color = "Quantile25/75"), linetype = "dashed") +
  geom_line(data = data.frame(do.call(cbind, res_pbmc10k_level1_train$fit)), aes(x = n, y = mean, color = "Train/Test"), linetype = "solid", size = 1) +
  scale_x_continuous(trans = log_trans(), breaks = c(1, 20, 40, 60, 80, 100, 500, 1000, 10000)) +
  scale_color_manual(values = cols) +
  theme_bw() +
  theme(legend.position = "bottom", aspect.ratio = 1)

ggsave("figures/FigureEV3B_learningCurve_pbmc10k_level1.pdf", width = 7, height = 5)
```






```{r}
res_pbmc10k_level1_pilot$plot +
   scale_x_continuous(trans = log_trans(), breaks = c(1, 20, 40, 60, 80, 100, 200, 500, 1000)) +
   theme(text = element_text(size = 14), aspect.ratio = 1)
ggsave("figures/figure3A_pbmc10k_level1.pdf", width = 6, height = 8)

ggplot(data = data.frame(do.call(cbind, res_pbmc10k_level1_pilot$fit)))  +
  xlab("N") + ylab("Classification Rate") +
  geom_point(data = data_pbmc10k_level1_train, aes(x = n, y = mean, color = "Train/Test")) +
  geom_line(data = data.frame(do.call(cbind, res_pbmc10k_level1_train$fit)), aes(x = n, y = mean, color = "Train/Test"), linetype = "solid", size = 1) +
  scale_x_continuous(trans = log_trans(), breaks = c(1, 20, 40, 60, 80, 100, 500, 1000, 10000)) +
  scale_color_manual(values = cols) +
  theme_bw() +
  theme(legend.position = "bottom", text = element_text(size = 14), aspect.ratio = 1)
ggsave("figures/figure3A_pbmc10k_level1_testTrain.pdf", width = 6, height = 8)



df_level1_concordance <- data.frame(data_pbmc10k_level1_pilot, 
                                    data_pbmc10k_level1_train[data_pbmc10k_level1_train$n %in% data_pbmc10k_level1_pilot$n, ],
                                    fit_pbmc10k_level1_pilot[which(fit_pbmc10k_level1_pilot$n %in% as.numeric(data_pbmc10k_level1_pilot$n)),]$mean)
colnames(df_level1_concordance) <- c("pilot_mean", "n", "train_mean", "train_n", "fit_n")
cor(df_level1_concordance$pilot_mean, df_level1_concordance$train_mean)
cor(df_level1_concordance$fit_n, df_level1_concordance$train_mean)

ggplot(data = df_level1_concordance, aes(x = fit_n, y = train_mean, color = (n)))  +
  xlab("Accuracy estimated by pilot data") + ylab("Accuracy from follow-up data") +
  geom_abline(intercept = 0 , slope = 1, size = 1, lty = 2, col = "grey30", alpha = 0.5) +
  geom_point(size = 3, alpha = 0.9) + 
  xlim(c(0.82,0.98)) + ylim(c(0.82,0.98)) +
  scale_color_viridis_c(option = "plasma", direction = -1, end = 0.9) +
  geom_text(aes(x = 0.95, y = 0.83, label = "Cor = 0.98"), color = "black", size = 6) +
  theme_bw() +
  theme(legend.position = "bottom", text = element_text(size = 14), aspect.ratio = 1,
        panel.border = element_rect(colour = "black", fill = NA, size = 1.2))
ggsave("figures/figure3B_pbmc10k_level1_scatter.pdf", width = 5, height = 6)


```


# PBMC10k level2

```{r fig.show = "hide"}

pbmc10k_level2_sampleCalRes_unblance_pilot <- readRDS("results/pbmc10k_level2_sampleCalRes_unblance_pilot.rds")
pbmc10k_level2_sampleCalRes_unblance_train <- readRDS("results/pbmc10k_level2_sampleCalRes_unblance_train.rds")



pilot_correct <- melt(lapply(pbmc10k_level2_sampleCalRes_unblance_pilot, function(x) unlist(lapply(x, "[[", "correct"))))

pilot_correct$L1 <- factor(pilot_correct$L1, levels = (unique(pilot_correct$L1)))


train_correct <- melt(lapply(pbmc10k_level2_sampleCalRes_unblance_train, function(x) unlist(lapply(x, "[[", "correct"))))

train_correct$L1 <- factor(train_correct$L1, levels = (unique(train_correct$L1)))

train_correct$type <- "train"
pilot_correct$type <- "pilot"
df_cbind <- rbind(pilot_correct, train_correct)

g1_level2 <- ggplot(df_cbind, aes(x = L1, y = value, color = type)) +
  geom_boxplot() + geom_jitter(alpha = 0.3) +
  scale_color_brewer(palette = "Set1") +
  theme_bw() +
  facet_wrap(~type, scales = "free_x") +
  xlab("N") + ylab("Classification Rate")
g1_level2
ggsave("figures/FigureEV3A_boxplot_learningCurve_pbmc10k_level2.pdf", width = 12, height = 5)
```



## Fitting learning curve


```{r}
acc_pbmc10k_level2_pilot <- lapply(pbmc10k_level2_sampleCalRes_unblance_pilot, function(x) unlist(lapply(x, "[[", "correct")))
acc_pbmc10k_level2_pilot <- acc_pbmc10k_level2_pilot[!is.null(acc_pbmc10k_level2_pilot)]

res_pbmc10k_level2_pilot <- learningCurve(acc_pbmc10k_level2_pilot,
                                  as.numeric(names(acc_pbmc10k_level2_pilot)),
                                  fitmodel = "nls_mix",
                                  d_list = seq(20, 200, 10))


```



```{r}
acc_pbmc10k_level2_train <- lapply(pbmc10k_level2_sampleCalRes_unblance_train, function(x) unlist(lapply(x, "[[", "correct")))
acc_pbmc10k_level2_train <- acc_pbmc10k_level2_train[!is.null(acc_pbmc10k_level2_train)]

res_pbmc10k_level2_train <- learningCurve(acc_pbmc10k_level2_train,
                                  as.numeric(names(acc_pbmc10k_level2_train)),
                                  fitmodel = "nls_mix",
                                  d_list = seq(50, 500, 10))

```


```{r}
pred_train <- predict(res_pbmc10k_level2_pilot$model$mean, newdata = data.frame(n = as.numeric(names(acc_pbmc10k_level2_train))))
```





```{r}

library(scales)


cols <- c("Pilot" = "indianred",
          "Quantile25/75" = "lightpink3" ,
          "Quantile05/95" = "white", 
          "Train/Test" = "dodgerblue4",
          "10X(V3)" = "#F28E2B")

data_pbmc10k_level2_pilot <- data.frame(mean = unlist(lapply(acc_pbmc10k_level2_pilot, mean)),
                         n = as.numeric(names(acc_pbmc10k_level2_pilot)))

data_pbmc10k_level2_train <- data.frame(mean = unlist(lapply(acc_pbmc10k_level2_train, mean)),
                         n = as.numeric(names(acc_pbmc10k_level2_train)))



fit_pbmc10k_level2_pilot <- data.frame(n = seq(20,8000, 0.1))
fit_pbmc10k_level2_pilot$mean <- predict(res_pbmc10k_level2_pilot$model$mean, newdata = fit_pbmc10k_level2_pilot)
fit_pbmc10k_level2_pilot$quantile_25 <- predict(res_pbmc10k_level2_pilot$model$quantile_25, newdata = fit_pbmc10k_level2_pilot)
fit_pbmc10k_level2_pilot$quantile_75 <- predict(res_pbmc10k_level2_pilot$model$quantile_75, newdata = fit_pbmc10k_level2_pilot)

```



```{r}

df_level2_concordance <- data.frame(data_pbmc10k_level2_pilot, 
                                    data_pbmc10k_level2_train[data_pbmc10k_level2_train$n %in% data_pbmc10k_level2_pilot$n, ],
                                    fit_pbmc10k_level2_pilot[which(fit_pbmc10k_level2_pilot$n %in% as.numeric(data_pbmc10k_level2_pilot$n)),]$mean)
colnames(df_level2_concordance) <- c("pilot_mean", "n", "train_mean", "train_n", "fit_n")
cor(df_level2_concordance$pilot_mean, df_level2_concordance$train_mean)


ggplot(data = df_level2_concordance, aes(x = fit_n, y = train_mean, color = (n)))  +
   xlab("Accuracy estimated by pilot data") + ylab("Accuracy from follow-up data") +
  geom_abline(intercept = 0 , slope = 1, size = 1, lty = 2, col = "grey30", alpha = 0.5) +
  geom_point(size = 3, alpha = 0.9) + 
  xlim(c(0.5,0.96)) + ylim(c(0.5,0.96)) +
  scale_color_viridis_c(option = "plasma", direction = -1, end = 0.9) +
  geom_text(aes(x = 0.9, y = 0.55, label = "Cor = 0.99"), color = "black", size = 6) +
  theme_bw() +
  theme(legend.position = "bottom", text = element_text(size = 14), aspect.ratio = 1,
        panel.border = element_rect(colour = "black", fill = NA, size = 1.2))
ggsave("figures/Figure3A_pbmc10k_level2_scatter.pdf", width = 5, height = 6)
```



```{r}

ggplot(data = fit_pbmc10k_level2_pilot)  +
  xlab("N") + ylab("Classification Rate") +
  labs(title = "PBMC10k level2") +
  geom_point(data = data_pbmc10k_level2_pilot, aes(x = n, y = mean, color = "Pilot")) +
  geom_point(data = data_pbmc10k_level2_train, aes(x = n, y = mean, color = "Train/Test")) +
  geom_line(aes(x = n, y = mean, color = "Pilot"), linetype = "solid", size = 1, lwd = 1) +
  geom_line(aes(x = n, y = quantile_25, color = "Quantile25/75"), linetype = "dashed") +
  geom_line(aes(x = n, y = quantile_75, color = "Quantile25/75"), linetype = "dashed") +
  geom_line(data = data.frame(do.call(cbind, res_pbmc10k_level2_train$fit)), aes(x = n, y = mean, color = "Train/Test"), linetype = "solid", size = 1, lwd = 1) +
  scale_x_continuous(trans = log_trans(), limits = c(80, 5000), breaks = c(100, 200, 500, 1000, 5000)) +
  ylim(c(0.6, 0.98)) +
  scale_color_manual(values = cols) +
  theme_bw() +
  theme(legend.position = "bottom", text = element_text(size = 14), aspect.ratio = 1) 


ggsave("figures/FigureEV3B_learningCurve_pbmc10k_level2.pdf", width = 7, height = 5)
```

# PBMC (levin)


```{r}
levin_pbmc_10x <- readRDS("results/sampleCalRes/levin_pbmc_10x_level2.rds")

levin_pbmc_10x_level1 <- readRDS("results/sampleCalRes/levin_pbmc_10x_level1.rds")


levin_pbmc_10xV2 <- readRDS("results/sampleCalRes/levin_pbmc_10xV2_level2.rds")
levin_pbmc_10xV2_level1 <- readRDS("results/sampleCalRes/levin_pbmc_10xV2_level1.rds")

### smartseq
levin_pbmc_smartseq <- readRDS("results/sampleCalRes/levin_pbmc_smartseq_level2.rds")
levin_pbmc_smartseq_level1 <- readRDS("results/sampleCalRes/levin_pbmc_smartseq_level1.rds")

### celseq
levin_pbmc_celseq <- readRDS("results/sampleCalRes/levin_pbmc_celseq_level2.rds")
levin_pbmc_celseq_level1 <- readRDS("results/sampleCalRes/levin_pbmc_celseq_level1.rds")


### inDrops

levin_pbmc_inDrops <- readRDS("results/sampleCalRes/levin_pbmc_inDrops_level2.rds")
levin_pbmc_inDrops_level1 <- readRDS("results/sampleCalRes/levin_pbmc_inDrops_level1.rds")

#### dropseqs

levin_pbmc_dropSeqs <- readRDS("results/sampleCalRes/levin_pbmc_dropSeqs_level2.rds")
levin_pbmc_dropSeqs_level1 <- readRDS("results/sampleCalRes/levin_pbmc_dropSeqs_level1.rds")

#### seqwells

levin_pbmc_seqWells <- readRDS("results/sampleCalRes/levin_pbmc_seqWells_level2.rds")
levin_pbmc_seqWells_level1 <- readRDS("results/sampleCalRes/levin_pbmc_seqWells_level1.rds")

```


## 10x (V3)

```{r}
levin_pbmc_10x <- lapply(levin_pbmc_10x, function(x) unlist(lapply(x, "[[", "correct")))
levin_pbmc_10x <- levin_pbmc_10x[!is.null(levin_pbmc_10x)]
accuracy_mat_10x <- do.call(cbind, levin_pbmc_10x)
res_10x <- learningCurve(accuracy_mat_10x, as.numeric(colnames(accuracy_mat_10x)))

levin_pbmc_10x_level1 <- lapply(levin_pbmc_10x_level1, function(x) unlist(lapply(x, "[[", "correct")))
levin_pbmc_10x_level1 <- levin_pbmc_10x_level1[!is.null(levin_pbmc_10x_level1)]
accuracy_mat_10x_level1 <- do.call(cbind, levin_pbmc_10x_level1)
res_10x_level1 <- learningCurve(accuracy_mat_10x_level1, as.numeric(colnames(accuracy_mat_10x_level1)))

```



## 10x (V2)

```{r}
levin_pbmc_10xV2 <- lapply(levin_pbmc_10xV2, function(x) unlist(lapply(x, "[[", "correct")))
levin_pbmc_10xV2 <- levin_pbmc_10xV2[!is.null(levin_pbmc_10xV2)]
accuracy_mat_10xV2 <- do.call(cbind, levin_pbmc_10xV2)
res_10xV2 <- learningCurve(accuracy_mat_10xV2, as.numeric(colnames(accuracy_mat_10xV2)))

levin_pbmc_10xV2_level1 <- lapply(levin_pbmc_10xV2_level1, function(x) unlist(lapply(x, "[[", "correct")))
levin_pbmc_10xV2_level1 <- levin_pbmc_10xV2_level1[!is.null(levin_pbmc_10xV2_level1)]
accuracy_mat_10xV2_level1 <- do.call(cbind, levin_pbmc_10xV2_level1)
res_10xV2_level1 <- learningCurve(accuracy_mat_10xV2_level1, as.numeric(colnames(accuracy_mat_10xV2_level1)))
```

## smart-seq

```{r}
levin_pbmc_smartseq <- lapply(levin_pbmc_smartseq, function(x) unlist(lapply(x, "[[", "correct")))
levin_pbmc_smartseq <- levin_pbmc_smartseq[!is.null(levin_pbmc_smartseq)]
accuracy_mat_smartseq <- do.call(cbind, levin_pbmc_smartseq)
res_smartseq <- learningCurve(accuracy_mat_smartseq[,-c(1:3)], as.numeric(colnames(accuracy_mat_smartseq[,-c(1:3)])))

levin_pbmc_smartseq_level1 <- lapply(levin_pbmc_smartseq_level1, function(x) unlist(lapply(x, "[[", "correct")))
levin_pbmc_smartseq_level1 <- levin_pbmc_smartseq_level1[!is.null(levin_pbmc_smartseq_level1)]
accuracy_mat_smartseq_level1 <- do.call(cbind, levin_pbmc_smartseq_level1)
res_smartseq_level1 <- learningCurve(accuracy_mat_smartseq_level1, as.numeric(colnames(accuracy_mat_smartseq_level1)))
```


## celseq

```{r}
levin_pbmc_celseq <- lapply(levin_pbmc_celseq, function(x) unlist(lapply(x, "[[", "correct")))
levin_pbmc_celseq <- levin_pbmc_celseq[!is.null(levin_pbmc_celseq)]
accuracy_mat_celseq <- do.call(cbind, levin_pbmc_celseq)
res_celseq <- learningCurve(accuracy_mat_celseq, as.numeric(colnames(accuracy_mat_celseq)))

levin_pbmc_celseq_level1 <- lapply(levin_pbmc_celseq_level1, function(x) unlist(lapply(x, "[[", "correct")))
levin_pbmc_celseq_level1 <- levin_pbmc_celseq_level1[!is.null(levin_pbmc_celseq_level1)]
accuracy_mat_celseq_level1 <- do.call(cbind, levin_pbmc_celseq_level1)
res_celseq_level1 <- learningCurve(accuracy_mat_celseq_level1, as.numeric(colnames(accuracy_mat_celseq_level1)))
```



## inDrops

```{r}
levin_pbmc_inDrops <- lapply(levin_pbmc_inDrops, function(x) unlist(lapply(x, "[[", "correct")))
levin_pbmc_inDrops <- levin_pbmc_inDrops[!is.null(levin_pbmc_inDrops)]
accuracy_mat_inDrops <- do.call(cbind, levin_pbmc_inDrops)
res_inDrops <- learningCurve(accuracy_mat_inDrops, as.numeric(colnames(accuracy_mat_inDrops)))

levin_pbmc_inDrops_level1 <- lapply(levin_pbmc_inDrops_level1, function(x) unlist(lapply(x, "[[", "correct")))
levin_pbmc_inDrops_level1 <- levin_pbmc_inDrops_level1[!is.null(levin_pbmc_inDrops_level1)]
accuracy_mat_inDrops_level1 <- do.call(cbind, levin_pbmc_inDrops_level1)
res_inDrops_level1 <- learningCurve(accuracy_mat_inDrops_level1, as.numeric(colnames(accuracy_mat_inDrops_level1)))
```



## dropSeqs

```{r}
levin_pbmc_dropSeqs <- lapply(levin_pbmc_dropSeqs, function(x) unlist(lapply(x, "[[", "correct")))
levin_pbmc_dropSeqs <- levin_pbmc_dropSeqs[!is.null(levin_pbmc_dropSeqs)]
accuracy_mat_dropSeqs <- do.call(cbind, levin_pbmc_dropSeqs)
res_dropSeqs <- learningCurve(accuracy_mat_dropSeqs, as.numeric(colnames(accuracy_mat_dropSeqs)))

levin_pbmc_dropSeqs_level1 <- lapply(levin_pbmc_dropSeqs_level1, function(x) unlist(lapply(x, "[[", "correct")))
levin_pbmc_dropSeqs_level1 <- levin_pbmc_dropSeqs_level1[!is.null(levin_pbmc_dropSeqs_level1)]
accuracy_mat_dropSeqs_level1 <- do.call(cbind, levin_pbmc_dropSeqs_level1)
res_dropSeqs_level1 <- learningCurve(accuracy_mat_dropSeqs_level1, as.numeric(colnames(accuracy_mat_dropSeqs_level1)))
```


## seqWells

```{r}
levin_pbmc_seqWells <- lapply(levin_pbmc_seqWells, function(x) unlist(lapply(x, "[[", "correct")))
levin_pbmc_seqWells <- levin_pbmc_seqWells[!is.null(levin_pbmc_seqWells)]
accuracy_mat_seqWells <- do.call(cbind, levin_pbmc_seqWells)
res_seqWells <- learningCurve(accuracy_mat_seqWells, as.numeric(colnames(accuracy_mat_seqWells)))

levin_pbmc_seqWells_level1 <- lapply(levin_pbmc_seqWells_level1, function(x) unlist(lapply(x, "[[", "correct")))
levin_pbmc_seqWells_level1 <- levin_pbmc_seqWells_level1[!is.null(levin_pbmc_seqWells_level1)]
accuracy_mat_seqWells_level1 <- do.call(cbind, levin_pbmc_seqWells_level1)
res_seqWells_level1 <- learningCurve(accuracy_mat_seqWells_level1, as.numeric(colnames(accuracy_mat_seqWells_level1)))
```


## Summary

```{r}
cols <- c("Mean" = "#c8133b",
          "Quantile25/75" = "#ea8783" ,
          "Quantile05/95" = "#feb5a2")

library(ggthemes)
cols <- tableau_color_pal(palette = "Tableau 10")(7)
names(cols) <- c("10X(V2)", "10X(V3)", "Smart-seq", "Cel-seq", "inDrops", "Drop-seq", "seqWells")

```


```{r}

fit_10xV2 <- data.frame(n = seq(20,10000, 0.1))
fit_10xV2$mean <- predict(res_10xV2$model$mean, newdata = fit_10xV2)


fit_10x <- data.frame(n = seq(20,10000, 0.1))
fit_10x$mean <- predict(res_10x$model$mean, newdata = fit_10x)

fit_celseq <- data.frame(n = seq(20,10000, 0.1))
fit_celseq$mean <- predict(res_celseq$model$mean, newdata = fit_celseq)

fit_smartseq <- data.frame(n = seq(20,10000, 0.1))
fit_smartseq$mean <- predict(res_smartseq$model$mean, newdata = fit_smartseq)

fit_inDrops <- data.frame(n = seq(20,10000, 0.1))
fit_inDrops$mean <- predict(res_inDrops$model$mean, newdata = fit_inDrops)

fit_dropSeqs <- data.frame(n = seq(20,10000, 0.1))
fit_dropSeqs$mean <- predict(res_dropSeqs$model$mean, newdata = fit_dropSeqs)

fit_seqWells <- data.frame(n = seq(20,10000, 0.1))
fit_seqWells$mean <- predict(res_seqWells$model$mean, newdata = fit_seqWells)

```



```{r}

fit_10xV2_level1 <- data.frame(n = seq(20,10000, 0.1))
fit_10xV2_level1$mean <- predict(res_10xV2_level1$model$mean, newdata = fit_10xV2_level1)


fit_10x_level1 <- data.frame(n = seq(20,10000, 0.1))
fit_10x_level1$mean <- predict(res_10x_level1$model$mean, newdata = fit_10x_level1)

fit_celseq_level1 <- data.frame(n = seq(20,10000, 0.1))
fit_celseq_level1$mean <- predict(res_celseq_level1$model$mean, newdata = fit_celseq_level1)

fit_smartseq_level1 <- data.frame(n = seq(20,10000, 0.1))
fit_smartseq_level1$mean <- predict(res_smartseq_level1$model$mean, newdata = fit_smartseq_level1)

fit_inDrops_level1 <- data.frame(n = seq(20,10000, 0.1))
fit_inDrops_level1$mean <- predict(res_inDrops_level1$model$mean, newdata = fit_inDrops_level1)

fit_dropSeqs_level1 <- data.frame(n = seq(20,10000, 0.1))
fit_dropSeqs_level1$mean <- predict(res_dropSeqs_level1$model$mean, newdata = fit_dropSeqs_level1)
# 
fit_seqWells_level1 <- data.frame(n = seq(20,10000, 0.1))
fit_seqWells_level1$mean <- predict(res_seqWells_level1$model$mean, newdata = fit_seqWells_level1)



```


```{r}
cols <- tableau_color_pal(palette = "Tableau 20")(14)
names(cols) <- c("10X(V2)", "10X(V2) (level1)", 
                 "10X(V3)", "10X(V3) (level1)", 
                 "Smart-seq", "Smart-seq (level1)", 
                 "Cel-seq", "Cel-seq (level1)", 
                 "inDrops", "inDrops (level1)", 
                 "Drop-seq", "Drop-seq (level1)", 
                 "seqWells", "seqWells (level1)")

```





```{r}

g_level2 <- ggplot2::ggplot()  +
  xlab("N") + ylab("Accuracy Rate") +
  geom_line(data = fit_10xV2, aes(x = n, y = mean, color = "10X(V2)"), linetype = "solid", size = 1) +
  geom_line(data = fit_10x, aes(x = n, y = mean, color = "10X(V3)"), linetype = "solid", size = 1) +
  geom_line(data = fit_smartseq, aes(x = n, y = mean, color = "Smart-seq"), linetype = "solid", size = 1) +
  geom_line(data = fit_celseq, aes(x = n, y = mean, color = "Cel-seq"), linetype = "solid", size = 1) +
  geom_line(data = fit_inDrops, aes(x = n, y = mean, color = "inDrops"), linetype = "solid", size = 1) +
  geom_line(data = fit_dropSeqs, aes(x = n, y = mean, color = "Drop-seq"), linetype = "solid", size = 1) +
  geom_line(data = fit_seqWells, aes(x = n, y = mean, color = "seqWells"), linetype = "solid", size = 1) +
  scale_color_manual(values = cols) +
  theme_bw() +
  scale_x_continuous(trans = log10_trans(), breaks = c(20, 50, 100, 200, 500, 1000, 5000, 10000)) +
  scale_y_continuous(breaks = seq(0,1,0.1)) + ylim(c(0,1)) + ylab("") +
  theme(legend.position = "bottom", text = element_text(size = 14), aspect.ratio = 1) +
  labs(title = "Level2")



g_level1 <- ggplot2::ggplot()  +
  xlab("N") + ylab("Accuracy Rate") +
  geom_line(data = fit_10xV2_level1, aes(x = n, y = mean, color = "10X(V2) (level1)"), linetype = "solid", size = 1) +
  geom_line(data = fit_10x_level1, aes(x = n, y = mean, color = "10X(V3) (level1)"), linetype = "solid", size = 1) +
  geom_line(data = fit_smartseq_level1, aes(x = n, y = mean, color = "Smart-seq (level1)"), linetype = "solid", size = 1) +
  geom_line(data = fit_celseq_level1, aes(x = n, y = mean, color = "Cel-seq (level1)"), linetype = "solid", size = 1) +
  geom_line(data = fit_inDrops_level1, aes(x = n, y = mean, color = "inDrops (level1)"), linetype = "solid", size = 1) +
  geom_line(data = fit_dropSeqs_level1, aes(x = n, y = mean, color = "Drop-seq (level1)"), linetype = "solid", size = 1) +
  geom_line(data = fit_seqWells_level1, aes(x = n, y = mean, color = "seqWells (level1)"), linetype = "solid", size = 1) +
  scale_color_manual(values = cols) +
  theme_bw() +
  scale_x_continuous(trans = log10_trans(), breaks = c(20, 50, 100, 200, 500, 1000, 5000, 10000)) +
  scale_y_continuous(breaks = seq(0,1,0.1)) + ylim(c(0,1)) +
  theme(legend.position = "bottom", text = element_text(size = 14), aspect.ratio = 1) +
  labs(title = "Level1")

g_level1
g_level2

pdf("figures/Figure3C_levinPBMC_sampleCal_learningCurve_levels.pdf", width = 12, height = 8)
grid.arrange(g_level1, g_level2, ncol = 2)
dev.off()
```



# DECENT simulation 



```{r}
rho_res_level2_pbmc10k <- readRDS("results/decent_rho_res_level2_pbmc10k.rds")
rho_res_level1_pbmc10k <- readRDS("results/decent_rho_res_level1_pbmc10k.rds")
```


```{r}
get_rho_res_level2 <- melt(rho_res_level2_pbmc10k)
get_rho_res_level1 <- melt(rho_res_level1_pbmc10k)
get_rho_res_level1$level <- "level 1"
get_rho_res_level2$level <- "level 2"

get_rho_res <- rbind(get_rho_res_level1, get_rho_res_level2)


ggplot(get_rho_res[get_rho_res$Var1 == "correct", ], aes(x = L1, y = value, color = level)) +
  geom_boxplot() +
  theme_bw() +
  stat_summary(fun.y = mean, geom = "line", lwd = 1, aes(group = level), alpha = 0.5) +
  scale_color_brewer(palette = "Set1") +
  ylim(c(0.6, 1)) +
  xlab("Rho") +
  ylab("Accuracy Rate") +
  theme(text = element_text(size = 14))
ggsave("figures/FigureEV3C_rho_res_pbmc10k_acc.pdf", width = 8, height = 5)


```



```{r}
res_decent_pbmc10k_level1_learningCurveRes <- readRDS("results/res_decent_pbmc10k_level1_learningCurveRes.rds")
res_decent_pbmc10k_level2_learningCurveRes <- readRDS("results/res_decent_pbmc10k_level2_learningCurveRes.rds")


rho_list <- c(0.1, 0.2, 0.5, 0.8, 1)

rho_res_level1_summary <- lapply(res_decent_pbmc10k_level1_learningCurveRes, function(list_alpha) {
  res <- lapply(1:length(res_decent_pbmc10k_level1_learningCurveRes[[1]][[1]]), function(idx) do.call(cbind, lapply(list_alpha, function(l) l[[idx]])))
  
  n_list <- c(seq(20, 100, 20), seq(200, 2000, 200))
  
  names(res) <- n_list
  # res <- melt(res)
  # res$L1 <- factor(res$L1, levels = n_list)
  res
})

names(rho_res_level1_summary) <- rho_list


rho_res_level1_summary_melt <- melt(rho_res_level1_summary[-1])



rho_res_level1_summary_melt$L2 <- factor(rho_res_level1_summary_melt$L2, levels = c(seq(20, 100, 20), seq(200, 2000, 200)))
rho_res_level1_summary_melt$L1 <- factor(rho_res_level1_summary_melt$L1, levels = rho_list[-1])

colnames(rho_res_level1_summary_melt) <- c("ErrorClass", "Iter", "value", "N", "prob")




rho_res_level2_summary <- lapply(res_decent_pbmc10k_level2_learningCurveRes, function(list_alpha) {
  res <- lapply(1:length(res_decent_pbmc10k_level2_learningCurveRes[[1]][[1]]), function(idx) do.call(cbind, lapply(list_alpha, function(l) l[[idx]])))
  
  n_list <- c(seq(20, 100, 20), seq(200, 2000, 200))
  
  names(res) <- n_list
  # res <- melt(res)
  # res$L1 <- factor(res$L1, levels = n_list)
  res
})

names(rho_res_level2_summary) <- rho_list



rho_res_level2_summary_melt <- melt(rho_res_level2_summary[-1])



rho_res_level2_summary_melt$L2 <- factor(rho_res_level2_summary_melt$L2, levels = c(seq(20, 100, 20), seq(200, 2000, 200)))
rho_res_level2_summary_melt$L1 <- factor(rho_res_level2_summary_melt$L1, levels = rho_list[-1])

colnames(rho_res_level2_summary_melt) <- c("ErrorClass", "Iter", "value", "N", "prob")


rho_res_level1_summary_melt$Level <- "level 1"
rho_res_level2_summary_melt$Level <- "level 2"
rho_res_summary_melt <- rbind(rho_res_level1_summary_melt, rho_res_level2_summary_melt)

```



```{r results = "hide"}


accMat_decent_list_level1 <- list()

for (i in 1:length(rho_list)) {
    accMat_decent_list_level1[[length(accMat_decent_list_level1) + 1]] <- lapply(rho_res_level1_summary[[i]], function(x) x[1,])
}



decent_learningCurve_fit_level1 <- list()

for(i in 1:length(accMat_decent_list_level1)) {
  decent_learningCurve_fit_level1[[i]] <- learningCurve(accMat_decent_list_level1[[i]],
                                  as.numeric(names(accMat_decent_list_level1[[i]])),
                                  fitmodel = "nls_mix",
                                  d_list = seq(20, 50, 10),
                                  b = 0.95)
  
}


decent_learningCurve_fit_fitted_level1 <- do.call(cbind, lapply(decent_learningCurve_fit_level1, function(x) x$fit$mean))
decent_learningCurve_fit_fitted_n_level1 <- decent_learningCurve_fit_level1[[1]]$fit$n

colnames(decent_learningCurve_fit_fitted_level1) <- rho_list
rownames(decent_learningCurve_fit_fitted_level1) <- decent_learningCurve_fit_fitted_n_level1
decent_learningCurve_fit_fitted_level1 <- melt(decent_learningCurve_fit_fitted_level1)


colnames(decent_learningCurve_fit_fitted_level1) <- c("N", "rho", "value")






accMat_decent_list_level2 <- list()

for (i in 1:length(rho_list)) {
    accMat_decent_list_level2[[length(accMat_decent_list_level2) + 1]] <- lapply(rho_res_level2_summary[[i]], function(x) x[1,])
}



decent_learningCurve_fit_level2 <- list()

for(i in 1:length(accMat_decent_list_level2)) {
  decent_learningCurve_fit_level2[[i]] <- learningCurve(accMat_decent_list_level2[[i]],
                                  as.numeric(names(accMat_decent_list_level2[[i]])),
                                  fitmodel = "nls_mix",
                                  d_list = seq(20, 50, 10))
}


decent_learningCurve_fit_fitted_level2 <- do.call(cbind, lapply(decent_learningCurve_fit_level2, function(x) x$fit$mean))
decent_learningCurve_fit_fitted_n_level2 <- decent_learningCurve_fit_level2[[1]]$fit$n

colnames(decent_learningCurve_fit_fitted_level2) <- rho_list
rownames(decent_learningCurve_fit_fitted_level2) <- decent_learningCurve_fit_fitted_n_level2
decent_learningCurve_fit_fitted_level2 <- melt(decent_learningCurve_fit_fitted_level2)



colnames(decent_learningCurve_fit_fitted_level2) <- c("N", "rho", "value")




decent_learningCurve_fit_fitted_level2$level <- "Level2"
decent_learningCurve_fit_fitted_level1$level <- "Level1"
decent_learningCurve_fit_fitted <- rbind(decent_learningCurve_fit_fitted_level1, decent_learningCurve_fit_fitted_level2)

```


```{r}
g1 <- ggplot(rho_res_summary_melt[rho_res_summary_melt$ErrorClass == "correct", ], aes(x = N, y = value, color = prob)) +
  geom_boxplot() +
  scale_color_viridis_d(option = "C", end = 0.8, direction = -1) +
  facet_wrap(~Level, nrow = 2) +
  ylim(c(0, 1)) +
  theme_bw() +
  ylab("Accuracy Rate") +
  theme(legend.position = "bottom", text = element_text(size = 14)) 

colnames(decent_learningCurve_fit_fitted) <- c("N", "prob", "value", "level")

g2 <- ggplot() +
  geom_line(data = decent_learningCurve_fit_fitted[decent_learningCurve_fit_fitted$prob!=0.1, ], aes(x = N, y = value, color = as.factor(prob), group = prob), lwd = 1, alpha = 0.8) +
  scale_color_viridis_d(option = "C", end = 0.8, direction = -1, guides(title = "prob")) +
  facet_wrap(~level, nrow = 2) +
  scale_x_continuous(limits = c(50, 2000), breaks = c(50, 200, seq(500, 2000, 250))) +
  ylim(c(0, 1)) +
  theme_bw() +
  ylab("Accuracy Rate") +
  theme(legend.position = "bottom", text = element_text(size = 14)) 
ggarrange(g1, g2, ncol = 2, align = "hv")

ggsave("figures/AppendixFigS5_decent_res_boxplot_learningCurve.pdf", width = 12, height = 8)

```



# SessionInfo


```{r}
sessionInfo()
```

